spring:
  application:
    name: SpringBootWork
  datasource:
    url: jdbc:mysql://localhost:3306/jwt_security?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useUnicode=true&autoReconnect=true&zeroDateTimeBehavior=CONVERT_TO_NULL
    username: root
    password: Alone117
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5           # 最小空闲连接数
      maximum-pool-size: 20     # 最大连接池大小
      auto-commit: true         # 自动提交事务
      connection-timeout: 30000 # 连接超时时间（毫秒）
      idle-timeout: 600000      # 空闲连接存活时间（毫秒）
      max-lifetime: 1800000     # 最大连接存活时间（毫秒）

  jpa:
    hibernate:
#      ddl-auto: update
      ddl-auto: create-drop
#    show-sql: true # 开发阶段设置为 true
    show-sql: false # 开发阶段设置为 true
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
      timeout: 1800000 # 使用毫秒格式，兼容 Redis Lettuce
      password: Alone117
      lettuce:
        pool:
          max-active: 20  # 最大连接数
          max-wait: -1    # 最大阻塞等待时间(负数表示无限制)
          max-idle: 5     # 最大空闲连接数
          min-idle: 0     # 最小空闲连接数

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # JWT 过期时间，1 天（毫秒）
      refresh-token:
        expiration: 604800000 # 刷新令牌过期时间，7 天（毫秒）

server:
  error:
    whitelabel:
      enabled: false # 禁用 Spring 默认错误页面
  port: 8080

logging:
  level:
    org.springframework.boot.autoconfigure: OFF # 禁用自动配置日志
    org.springframework: DEBUG # Spring 调试日志级别
    com.david.hlp.SpringBootWork.auth.mapper: DEBUG
    org.mybatis: DEBUG

# MyBatis-Plus 配置
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  mapper-locations: classpath*:/mapper/**/*.xml
#  typeAliasesPackage: com.david.hlp.SpringBootWork.user # 指定实体类所在包

